/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movie.ticket;

import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Raheez
 */
public class bookTicket extends javax.swing.JFrame {
    Connection connection = null;
    Connection connection2 = null;
    PreparedStatement prp = null;
    ResultSet result = null;
    PreparedStatement prp2 = null;
    ResultSet result2 = null;
    String userId;
    int screen;
    String ThId;
    static JPanel panel;
    /**
     * Creates new form bookTicket
     */
    public bookTicket() {
        initComponents();
        
    }
    public bookTicket(String Uid) {
        initComponents();
        userId = Uid;
    }
    
    
    public void loadshowPanel(int len,int sno,String tid){
        jPanel1.removeAll();
        screen = sno;
        ThId =tid;
        panel  = new JPanel(new GridLayout(11,11));
        panel.setSize(500,500);
        connection = Connector.ConnectDb();
        for ( int i = 0; i <= len; i++ ) 
                {                    
                    JButton button = new JButton( String.valueOf(i) );
                    button.setSize(10, 10);
                   
                    
                    String sql = "select seatno from ticket where screenno = "+sno+" and tid='"+tid+"' and seatno="+i;
                    try{
                         
                        
                        prp = connection.prepareStatement(sql);
                        result = prp.executeQuery();
                        result.next();
                        if(result.getInt("seatno")==i){
                            
                            button.setBackground(new java.awt.Color(255, 51, 51));
                        }
                        panel.add( button ) ; 
                        
                        
                    }
                    catch(SQLException e){
                        panel.add( button );
                    }
                    
                    
                       
                }
                               jPanel1.add(panel);
                               jPanel1.revalidate();
                               System.out.println(len);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(43, 58, 85));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mangalore", "Bangalore", "Mysore", "Hassan", "Kasargod", "Udupi", "Mumbai", "Delhi" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 52, 140, -1));

        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 52, 147, -1));

        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 52, 135, -1));

        jButton1.setText("Fetch Theatre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 23, 147, -1));

        jButton2.setText("Fetch Shows");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 23, 130, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 130, -1));

        jButton3.setText("BOOK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ami R", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEAT NO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 90, -1));

        jLabel2.setFont(new java.awt.Font("Ami R", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Location");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 140, -1));

        jButton4.setText("Featch seats");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 110, -1));

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 60, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int itemCount = jComboBox2.getItemCount();

    for(int i = 0; i < itemCount; i++){
        jComboBox2.removeItemAt(0);
    }
        
       String select = (String)jComboBox1.getSelectedItem();
       String sql = "select name from theatre where location = '"+select+"'";
       
       connection = Connector.ConnectDb();
        try{
            prp = connection.prepareStatement(sql);
            result = prp.executeQuery();
            
            while(result.next()){
                jComboBox2.addItem(result.getString("name"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "NO screens available");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           
   int itemCount = jComboBox3.getItemCount();

    for(int i = 0; i < itemCount; i++){
        jComboBox3.removeItemAt(0);
    }
        
       String select = (String)jComboBox2.getSelectedItem();
       String sql = "select id from theatre where name = '"+select+"'";
       
       connection = Connector.ConnectDb();
        try{
            prp = connection.prepareStatement(sql);
            result = prp.executeQuery();
            
            while(result.next()){
                String sql2 = "select movie from shows where tid = '"+result.getString("id")+"'";
                connection2 = Connector.ConnectDb();
                prp2 = connection2.prepareStatement(sql2);
                result2 = prp2.executeQuery();
                
                while(result2.next()){

                    jComboBox3.addItem(result2.getString("movie"));
                }
                
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "NO screens available");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String selectt = (String)jComboBox2.getSelectedItem();
        String select = (String)jComboBox3.getSelectedItem();
        String Tid;
        int sno;
        int seats;
       
        String sql = "select id from theatre where name = '"+selectt+"'";
        connection = Connector.ConnectDb();
        connection2 = Connector.ConnectDb();
        try{
            prp = connection.prepareStatement(sql);
            result = prp.executeQuery();
            
            result.next();
            Tid = result.getString("id");
            String sql2 = "select seats,screenno,price from shows where tid='"+Tid+"' and movie = '"+select+"'";
            prp2 = connection2.prepareStatement(sql2);
            result2 = prp2.executeQuery();
            result2.next();
            seats = result2.getInt("seats");
            sno = result2.getInt("screenno");
            jLabel4.setText("RS."+result2.getString("price"));
            loadshowPanel(seats,sno,Tid);
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       connection = Connector.ConnectDb();
        if (connection != null) {
           String UID = userId;
           int seatno = Integer.parseInt(jTextField1.getText());
           int screenno = screen;
           String TID =ThId;
            
            String sql = "insert into ticket(uid,seatno,screenno,tid) values (?,?,?,?)";
            
            try {
                prp = connection.prepareStatement(sql);
                prp.setString(1, UID);
                prp.setInt(2, seatno);
                prp.setInt(3, screenno);
                prp.setString(4, TID);
                prp.execute();
                
                JOptionPane.showMessageDialog(null, "Ticket Booked");
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Ticket not available ");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        userActivity user = new userActivity(userId);
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
